package com.example.youtubeapp.data.model

data class Video(
    val id: String,
    val title: String,
    val description: String,
    val thumbnailUrl: String,
    val channelTitle: String,
    val channelId: String,
    val publishedAt: String,
    val duration: String = "",
    val viewCount: Long = 0,
    val likeCount: Long = 0
)

data class Playlist(
    val id: String,
    val title: String,
    val description: String,
    val thumbnailUrl: String,
    val itemCount: Int
)

data class Channel(
    val id: String,
    val title: String,
    val description: String,
    val thumbnailUrl: String,
    val subscriberCount: Long = 0,
    val videoCount: Long = 0
)

data class SearchResult(
    val videos: List<Video>,
    val nextPageToken: String? = null
)

data class VideoDetails(
    val video: Video,
    val tags: List<String> = emptyList(),
    val categoryId: String = "",
    val defaultLanguage: String = ""
)

data class CaptionTrack(
    val languageCode: String,
    val languageName: String,
    val url: String,
    val isAutoGenerated: Boolean = false
)
